SET IDENTITY_INSERT [dbo].[Staff] ON
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (1, N'Manager', N'Example', N'Manager', N'manager123', N'Manager123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (2, N'Mechanic', N'Example', N'Mechanic', N'mechanic123', N'Mechanic123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (3, N'John', N'Gates', N'Senior Mechanic', N'jdog34', N'TheJDog!*3', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (4, N'Initiate', N'Example', N'Initiate', N'initiate123', N'Initiate123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (5, N'Senior  Mechanic', N'Example', N'Senior Mechanic', N'smechanic123', N'Smechanic123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (6, N'Brenda', N'Gates', N'Initiate', N'bGates203', N'BigDoc12!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (7, N'Brendan', N'Gates', N'Initiate', N'bGates356', N'Bossman3000*', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (8, N'Jeremy', N'Gates', N'Manager', N'jerry', N'Jeremy99%', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (9, N'Liberia', N'Gates', N'Initiate', N'lib23', N'Password42!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (10, N'Moriah', N'Gates', N'Initiate', N'mori7', N'Password43!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (11, N'Ryan', N'Gates', N'Initiate', N'ryga11', N'Password44!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (12, N'Jackie', N'Gates', N'Initiate', N'jGates204', N'Password45!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (13, N'Jim', N'Gates', N'Initiate', N'JimmyG', N'Password56!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (14, N'John', N'Jamison', N'Mechanic', N'john12', N'Quizzy123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (15, N'Jack', N'Jacobs', N'Initiate', N'jack45', N'Qwerty12345!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (16, N'Pete', N'Doug', N'Initiate', N'pete34', N'Test12345!"', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (17, N'Dave', N'Cherry', N'Initiate', N'davec', N'Password12344!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (18, N'Joe', N'Bloggs', N'Initiate', N'joeb', N'Password12345!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (19, N'Cormac', N'Peters', N'Initiate', N'corpet', N'Password123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (20, N'Finn', N'Smith', N'Initiate', N'user356', N'Password127!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (21, N'John', N'Smith', N'Initiate', N'user146', N'Password129!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (22, N'abby', N'Bonfer', N'Initiate', N'abbon', N'Password1!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (23, N'Abby-May', N'Smith-Jones', N'Initiate', N'abby12', N'Abby''Smith1!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (24, N'Jonah', N'Jacks', N'Initiate', N'jonahJ23', N'Password163!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (25, N'Jo', N'Smithy', N'Initiate', N'JoS92', N'Password184!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (26, N'Abby Jane', N'Pentelberry-Smy', N'Initiate', N'user123@', N'Password166!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (27, N'Mistress Sarah Jane', N'Pentlebury-Smyth IV', N'Initiate', N'sarahjane', N'Password1231!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (28, N'Julie-Ann', N'Darge', N'Initiate', N'jann', N'Thewrok:@@', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (29, N'Harry', N'Jenson', N'Initiate', N'HaJe92', N'gggggggG2''', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (30, N'Joseph', N'Coulter', N'Initiate', N'theoldmototoad', N'Testing123###', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (31, N'James', N'Reacher', N'Initiate', N'Cjww22', N'Plos23@:', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (32, N'Jo', N'No', N'Initiate', N'Jo12', N'JoLove12!', 1)
SET IDENTITY_INSERT [dbo].[Staff] OFF
