SET IDENTITY_INSERT [dbo].[Staff] ON
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (1, N'Manager', N'Gates', N'Manager', N'manager123', N'Manager123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (2, N'Mechanic', N'Gates', N'Mechanic', N'mechanic123', N'Mechanic123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (3, N'John', N'Gates', N'Senior Mechanic', N'ceo', N'ceo', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (4, N'Initiate', N'Gates', N'Initiate', N'initiate123', N'Initiate123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (5, N'Senior Mechanic', N'Gates', N'Senior Mechanic', N'smechanic123', N'Smechanic123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (6, N'Brenda', N'Gates', N'Initiate', N'username2', N'password2', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (7, N'Brendan', N'Gates', N'Initiate', N'username3', N'password3', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (8, N'Jeremy', N'Gates', N'Manager', N'', N'', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (9, N'Liberia', N'Gates', N'Initiate', N'username4', N'Password4!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (10, N'Moriah', N'Gates', N'Initiate', N'username4', N'Password4!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (11, N'Ryan', N'Gates', N'Initiate', N'username4', N'Password4!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (12, N'Jackie', N'Gates', N'Initiate', N'username4', N'Password4!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (13, N'Jim', N'Gates', N'Initiate', N'username5', N'Password5!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (14, N'a', N'a', N'Mechanic', N'a', N'Quizzy123!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (15, N'q', N'q', N'Initiate', N'q', N'Qwerty12345!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (16, N'test1', N'test1', N'Initiate', N'test1', N'Test12345!"', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (17, N'Dave', N'Cherry', N'Initiate', N'davec', N'Password12344!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (18, N'Joe', N'Bloggs', N'Initiate', N'joeb', N'Password12345!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (19, N'e', N'w', N'Initiate', N'k', N'Password123!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (20, N'John', N'Smith', N'Initiate', N'username123', N'Password123!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (21, N'John', N'Smith', N'Initiate', N'username124', N'Password123!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (22, N'abby', N'b', N'Initiate', N'abcd', N'Password1!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (23, N'Abby-May', N'Smith-Jones', N'Initiate', N'abby', N'Abby''Smith1!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (24, N'New', N'Bie', N'Initiate', N'abcdef', N'Password1!', 0)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (25, N'Jo', N'Smithy', N'Initiate', N'abc123', N'Password1!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (26, N'Abby Jane', N'Pentelberry-Smy', N'Initiate', N'user123', N'Password1!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (27, N'Mistress Sarah Jane', N'Pentlebury-Smyth IV', N'Initiate', N'sarahjane', N'Password1!', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (28, N'Julie-Ann', N'Darge', N'Initiate', N'jann', N'Tw,2!efee', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (29, N'erfreer', N'g', N'Initiate', N'gggg', N'gggggggG2''', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (30, N'Joseph', N'Coulter', N'Initiate', N'theoldmototoad', N'Testing123###', 1)
INSERT INTO [dbo].[Staff] ([StaffId], [Forename], [Surname], [StaffPosition], [Username], [Password], [Active]) VALUES (31, N'v', N'a', N'Initiate', N'c234', N'rMioefkp,dlkr3e', 1)
SET IDENTITY_INSERT [dbo].[Staff] OFF
