USE [C:\USERS\ANDRE\ONEDRIVE\DESKTOP\A2 SSD\TASKS\FINAL PROJECT\FINAL PROJECT\FINAL PROJECT\STOCKMANAGEMENT.MDF]
GO

/****** Object: SqlProcedure [dbo].[UpdateStaffStatus] Script Date: 27/01/2025 21:04:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[UpdateStaffStatus]
	@StaffId int,
	@Active int
AS
	UPDATE Staff SET Active = @Active 
	WHERE StaffId = @StaffId
RETURN 0
