using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;
using Final_Project.Models;
using Final_Project.Data_Access;

namespace Final_Project
{
	// Manage access to the Order and OrderItem tables
	public class OrderDal
    {
		// Get connection string using DalHelper class
		private static string _connectionstring = DalHelper._connectionstring;

		// Create a new order
		public static Order AddOrder(Order newOrder)
		{
			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Call AddOrder stored procedure
				connection.Open();
				SqlCommand insertOrderCommand = new SqlCommand();
				insertOrderCommand.Connection = connection;
				insertOrderCommand.CommandType = System.Data.CommandType.StoredProcedure;
				insertOrderCommand.CommandText = "AddOrder";
				// Set OrderNumber as an output parameter to get autogenerated id from database
				SqlParameter dbOrderNumber = new SqlParameter("@OrderNumber", newOrder.orderNumber);
				dbOrderNumber.Direction = System.Data.ParameterDirection.Output;
				insertOrderCommand.Parameters.Add(dbOrderNumber);
				insertOrderCommand.Parameters.Add(new SqlParameter("@OrderDate", newOrder.orderDate));
				insertOrderCommand.Parameters.Add(new SqlParameter("@OrderPlacedByStaffId", newOrder.orderPlacedByStaffId));
				insertOrderCommand.Parameters.Add(new SqlParameter("@OrderStatus", newOrder.orderStatus));

				// Get number of rows affected
				int rowsAffected = insertOrderCommand.ExecuteNonQuery();
				if (rowsAffected > 0)
				{
					// If a row was updated, get the autogenerated OrderNumber
					newOrder.orderNumber = Convert.ToInt32(dbOrderNumber.Value);
				}
				else
				{
					// Otherwise set the OrderNumber to 0 to indicate an error
					newOrder.orderNumber = 0;
				}
				connection.Close();

				// Return the order number with the new id (or 0 for an error)
				return newOrder;
			}
		}

		// Add an order item to an order
		public static int AddOrderItem(OrderItem newOrderItem)
		{
			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Call AddOrderItem stored procedure
				connection.Open();
				SqlCommand insertOrderItemCommand = new SqlCommand();
				insertOrderItemCommand.Connection = connection;
				insertOrderItemCommand.CommandType = System.Data.CommandType.StoredProcedure;
				insertOrderItemCommand.CommandText = "AddOrderItem";
				insertOrderItemCommand.Parameters.Add(new SqlParameter("@OrderNumber", newOrderItem.orderNumber));
				insertOrderItemCommand.Parameters.Add(new SqlParameter("@StockId", newOrderItem.stockId));
				insertOrderItemCommand.Parameters.Add(new SqlParameter("@OrderItemQuantity", newOrderItem.orderItemQuantity));

				// Get the number of rows affected
				int rowsAffected = insertOrderItemCommand.ExecuteNonQuery();
				connection.Close();

				// Return the number of rows affected (0 for an error; 1 successful)
				return rowsAffected;
			}
		}

		// Update the status of an order
		public static int UpdateOrderStatus(Order order)
		{
			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Call UpdateOrderStatus stored procedure
				connection.Open();
				SqlCommand updateOrderStatusCommand = new SqlCommand();
				updateOrderStatusCommand.Connection = connection;
				updateOrderStatusCommand.CommandType = System.Data.CommandType.StoredProcedure;
				updateOrderStatusCommand.CommandText = "UpdateOrderStatus";
				updateOrderStatusCommand.Parameters.Add(new SqlParameter("@OrderNumber", order.orderNumber));
				updateOrderStatusCommand.Parameters.Add(new SqlParameter("@OrderStatus", order.orderStatus));

				// Get the number of rows affected
				int rowsAffected = updateOrderStatusCommand.ExecuteNonQuery();
				connection.Close();

				// Return the number of rows affected (0 for an error; 1 successful)
				return rowsAffected;
			}
		}

		// Store the id of the staff memeber who placed an an order
		public static int SetOrderPlacedBy(Order newOrder)
		{
			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Call SetOrderPlacedBy stored procedure
				connection.Open();
				SqlCommand updateOrderPlacedByCommand = new SqlCommand();
				updateOrderPlacedByCommand.Connection = connection;
				updateOrderPlacedByCommand.CommandType = System.Data.CommandType.StoredProcedure;
				updateOrderPlacedByCommand.CommandText = "SetOrderPlacedBy";
				updateOrderPlacedByCommand.Parameters.Add(new SqlParameter("@OrderNumber", newOrder.orderNumber));
				updateOrderPlacedByCommand.Parameters.Add(new SqlParameter("@OrderPlacedByStaffId", newOrder.orderPlacedByStaffId));

				// Get the number of rows affected
				int rowsAffected = updateOrderPlacedByCommand.ExecuteNonQuery();
				connection.Close();

				// Return the number of rows affected (0 for an error; 1 successful)
				return rowsAffected;
			}
		}

		// Remove an item from an order
		public static int RemoveOrderItem(OrderItem orderItemToRemove)
		{
			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Call the RemoveOrderItem stored procedure
				connection.Open();
				SqlCommand removeOrderItemCommand = new SqlCommand();
				removeOrderItemCommand.Connection = connection;
				removeOrderItemCommand.CommandType = System.Data.CommandType.StoredProcedure;
				removeOrderItemCommand.CommandText = "RemoveOrderItem";
				removeOrderItemCommand.Parameters.Add(new SqlParameter("@OrderNumber", orderItemToRemove.orderNumber));
				removeOrderItemCommand.Parameters.Add(new SqlParameter("@StockId", orderItemToRemove.stockId));

				// Get the number of rows affected
				int rowsAffected = removeOrderItemCommand.ExecuteNonQuery();
				connection.Close();

				// Return the number of rows affected (0 for an error; 1 successful)
				return rowsAffected;
			}
		}

		// Get a list of all orders
		// Takes 'ASC' or 'DESC' to sort by increating or decreasing order number
		public static List<Order> GetAllOrders(string orderBy)
		{
			List<Order> orders = new List<Order>();

			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Build and run SQL query to get all orders
				connection.Open();
				string sqlQuery = "SELECT * FROM [Order] ORDER BY OrderNumber ";
				// Check parameter passed is either 'ASC' or 'DESC' before adding to SQL to avoid risk of SQL injection
				if (orderBy == "DESC" || orderBy == "ASC")
					sqlQuery += orderBy;
				SqlCommand getAllOrdersCommand = new SqlCommand(sqlQuery, connection);
				SqlDataReader sqlDataReader = getAllOrdersCommand.ExecuteReader();

				// Create an order onject for each row returned (without optional delivery details values)
				while (sqlDataReader.Read())
				{
					Order order = new Order(

						(int)sqlDataReader["OrderNumber"],
						(DateTime)sqlDataReader["OrderDate"],
						(int)sqlDataReader["OrderPlacedByStaffId"],
						(string)sqlDataReader["OrderStatus"]
					);
					orders.Add(order);
				}
				connection.Close();
			}

			// Return list of Order objects
			return orders;
		}

		// Get list of order items for an order
		public static List<OrderItem> GetAllOrderItems(int orderNumber)
        {
			List<OrderItem> orderItems = new List<OrderItem>();

			using (SqlConnection connection = new SqlConnection(_connectionstring))
            {
				// Build and run SQL query to get order items for an order
				connection.Open();
				string sqlQuery = $"SELECT * FROM OrderItem WHERE OrderNumber = {orderNumber}";
                SqlCommand getAllOrderItemsCommand = new SqlCommand(sqlQuery, connection);
                SqlDataReader sqlDataReader = getAllOrderItemsCommand.ExecuteReader();

				// Create an order item object for each row returned
				while (sqlDataReader.Read())
                {
					OrderItem orderItem = new OrderItem(
                        (int)sqlDataReader["OrderNumber"],
                        (int)sqlDataReader["StockId"],
                        (int)sqlDataReader["OrderItemQuantity"]                        
                        );
                    orderItems.Add(orderItem);
                }
                connection.Close();

				// Return list of OrderItem objects
				return orderItems;
            }
        }

		// Get an order using the OrderNumber
		public static Order GetOrderByOrderNumber(int orderNumber)
		{
			Order order = new Order();

			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Build and run SQL query to get an order by its OrderNumber
				connection.Open();
				string sqlQuery = string.Format($"SELECT * FROM [Order] WHERE OrderNumber = {orderNumber}");
				SqlCommand getOrderByOrderNumber = new SqlCommand(sqlQuery, connection);
				SqlDataReader sqlDataReader = getOrderByOrderNumber.ExecuteReader();

				// Create an order object if a row is returned (without optional delivery details values)
				while (sqlDataReader.Read())
				{
					order = new Order(
						(int)sqlDataReader["OrderNumber"],
						(DateTime)sqlDataReader["OrderDate"],
						(int)sqlDataReader["OrderPlacedByStaffId"],
						(string)sqlDataReader["OrderStatus"]
						);
				}
				connection.Close();

				// Return an Order object
				return order;
			}
		}

		// Get a list of all orders, including delivery details
		// Uses a database view to combine information from multiple tables
		public static List<Order> GetAllOrdersWithDeliveryDetails()
		{
			List<Order> orders = new List<Order>();

			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Build and run SQL query to the orders, including deliver details, from the OrdersView database view
				connection.Open();
				string sqlQuery = "SELECT * FROM [OrdersView] ORDER BY OrderNumber DESC";
				SqlCommand getAllOrdersCommand = new SqlCommand(sqlQuery, connection);
				SqlDataReader sqlDataReader = getAllOrdersCommand.ExecuteReader();

				// Create an order object for each row returned, setting optional delivery details values
				while (sqlDataReader.Read())
				{
					Order order = new Order(
						(int)sqlDataReader["OrderNumber"],
						(DateTime)sqlDataReader["OrderDate"],
						(int)sqlDataReader["OrderPlacedByStaffId"],
						(string)sqlDataReader["OrderStatus"],
						DalHelper.GetSqlString(sqlDataReader, "OrderPlacedByStaffName"),
						DalHelper.GetSqlDate(sqlDataReader, "MinDeliveryDueDate"),
						DalHelper.GetSqlDate(sqlDataReader, "MaxDeliveryDueDate"),
						DalHelper.GetSqlDate(sqlDataReader, "LastDeliveryDate")
					);
					orders.Add(order);
				}
				connection.Close();

				// Return a list of Order object (including delivery details)
				return orders;
			}
		}

		// Get list of all order items that have discrepancies (orders with missing/faulty items)
		// Uses OrderItemsDeliveredView database view
		public static List<OrderItemsDeliveredView> GetOrderItemDiscrepancies()
		{
			List<OrderItemsDeliveredView> orderItemsDelivered = new List<OrderItemsDeliveredView>();

			using (SqlConnection connection = new SqlConnection(_connectionstring))
			{
				// Build and run SQL query to get order discrepancies
				// Uses OrderItemsDeliveredView database view and checks for order items with missing/faulty items
				// i.e. the quantity delivered minus the quantity faulty is less than the number ordered
				string sqlQuery =
					"SELECT * " +
					"FROM OrderItemsDeliveredView " +
					"WHERE (QuantityDelivered - QuantityFaulty) < OrderItemQuantity " +
					"ORDER BY OrderNumber DESC";
				connection.Open();
				SqlCommand getAllOrderItemsDeliveredCommand = new SqlCommand(sqlQuery, connection);
				SqlDataReader sqlDataReader = getAllOrderItemsDeliveredCommand.ExecuteReader();

				// Create an OrderItemsDeliveredView object for each row returned
				while (sqlDataReader.Read())
				{
					OrderItemsDeliveredView orderItemDelivered = new OrderItemsDeliveredView(
						(int)sqlDataReader["OrderNumber"],
						(int)sqlDataReader["StockId"],
						(string)sqlDataReader["StockName"],
						(int)sqlDataReader["OrderItemQuantity"],
						(DateTime)sqlDataReader["DeliveryDate"],
						(int)sqlDataReader["QuantityDelivered"],
						(int)sqlDataReader["QuantityFaulty"]
						);
					orderItemsDelivered.Add(orderItemDelivered);
				}
				connection.Close();

				// Return a list of OrderItemsDeliveredView objects
				return orderItemsDelivered;
			}
		}
	}
}
